import os, sys
sys.path.append(os.getcwd()) #添加进环境变量，实现跨文件调用
import pandas as pd
from data.table_define import FileTable

# 接入网onu（光衰）
root_dir = 'code/data/'
match_pattern = r'DWA_M_CUST_PERCEP_PREDIC_MON_202405_008'
"""建表语句参考
CREATE TABLE DWA_M_CUST_PERCEP_PREDIC_MON
(
    `month_id` String COMMENT '账期',
    `area_no` Nullable(String) COMMENT '地市编码',
    `area_name` String COMMENT '地市名称',
    `user_no` Nullable(String) COMMENT '用户ID',
    `device_number` String COMMENT '电话号码',
    `cust_no` Nullable(String) COMMENT '客户ID',
    `cust_name` Nullable(String) COMMENT '客户名称',
    `cust_type` Nullable(String) COMMENT '客户类型',
    `city_no` Nullable(String) COMMENT '县区MAP_CITY',
    `city_name` Nullable(String) COMMENT '归属县分名称',
    `user_name` Nullable(String) COMMENT '用户名称',
    `sex` Nullable(String) COMMENT '性别标识',
    `age` Nullable(String) COMMENT '用户年龄',
    `channel_no` Nullable(String) COMMENT 'DEVELOP_DEPART_ID发展渠道编码',
    `depart_name` Nullable(String) COMMENT '渠道名称',
    `VIP_CLASS` Nullable(String) COMMENT 'VIP等级',
    `is_lh` Nullable(String) COMMENT '是否靓号',
    `INNET_MONTH` Nullable(String) COMMENT '在网时长',
    `tele_type_desc` Nullable(String) COMMENT '业务类型',
    `TELE_TYPE_NET` Nullable(String) COMMENT '总部下发网络类型--移动业务用户',
    `brand_no` Nullable(String) COMMENT '品牌',
    `CONTACT_NBR` Nullable(String) COMMENT '联系电话',
    `CREDIT_CLASS` Nullable(String) COMMENT '信用等级',
    `user_status_desc` Nullable(String) COMMENT '用户状态',
    `is_fk` Nullable(String) COMMENT '是否副卡',
    `kd_device_number` Nullable(String) COMMENT '宽带号码',
    `kd_web_type` Nullable(String) COMMENT '宽带资费类型',
    `kd_start_date` Nullable(String) COMMENT '宽带资费开始时间',
    `kd_end_date` Nullable(String) COMMENT '宽带资费结束时间',
    `kd_rate_value` Nullable(String) COMMENT '宽带速率',
    `kd_is_qz` Nullable(String) COMMENT '是否千兆宽带',
    `kd_install_addr` Nullable(String) COMMENT '装机地址',
    `VILLAGE_NO` Nullable(String) COMMENT '小区编码',
    `TERM_NETWORK_TYPE` Nullable(String) COMMENT '终端制式',
    `TERM_BRAND` Nullable(String) COMMENT '终端品牌',
    `TERM_MODE` Nullable(String) COMMENT '终端型号',
    `TERM_SYSTEM` Nullable(String) COMMENT '操作系统',
    `TERM_MIZE_TYPE` Nullable(String) COMMENT '联通U/电信T/移动定制M',
    `TERM_UNICOM_TYPE` Nullable(String) COMMENT '终端最高登录联通网络能力为联通4G/3G/2G',
    `TERM_REGISTER_TIME` Nullable(String) COMMENT '换机时间',
    `is_2kc` Nullable(String) COMMENT '是否2卡槽（单双卡）',
    `product_id` Nullable(String) COMMENT '产品（PRODUCT_ID）',
    `product_name` Nullable(String) COMMENT '产品名称',
    `PROD_TYPE` Nullable(String) COMMENT '产品大类DWCODE.DIM_PROD_TYPE',
    `PURCHASE_IF_USE` Nullable(String) COMMENT '合约是否当前在用',
    `PURCHASE_TYPE` Nullable(String) COMMENT '合约类型',
    `PURCHASE_START_DATE` Nullable(String) COMMENT '合约开始时间',
    `PURCHASE_END_DATE` Nullable(String) COMMENT '合约结束时间',
    `is_card` Nullable(String) COMMENT '是否上网卡',
    `is_cndx` Nullable(String) COMMENT '是否承诺低消用户',
    `start_date` Nullable(String) COMMENT '承诺低消生效时间',
    `is_bjl_u` Nullable(String) COMMENT '是否冰激凌套餐用户',
    `user_type` Nullable(String) COMMENT '用户类型（2/3/4/5G--采用登网口径）',
    `total_fee` Nullable(String) COMMENT 'ARPU（元/月）',
    `call_duration` Nullable(String) COMMENT 'MOU（分钟/月）',
    `CALL_OUT_JF` Nullable(String) COMMENT '通话主叫计费时长',
    `CALL_IN_JF` Nullable(String) COMMENT '通话被叫计费时长',
    `CALL_ROAM_JF` Nullable(String) COMMENT '通话漫游计费时长',
    `flux_dou` Nullable(String) COMMENT 'DOU（MB/月）',
    `FLUX_2G` Nullable(String) COMMENT '2G流量',
    `FLUX_3G` Nullable(String) COMMENT '3G流量',
    `FLUX_4G` Nullable(String) COMMENT '4G流量',
    `FLUX_5G` Nullable(String) COMMENT '5G流量(新增字段数据自202004账期起)',
    `is_ll_ct` Nullable(String) COMMENT '是否流量超套（否：0；是：超套多少费用）',
    `is_yy_ct` Nullable(String) COMMENT '是否语音超套（否：0；是：超套多少费用）',
    `product_name_5g_sjb` Nullable(String) COMMENT '是否办理5G升级包(办理的升级包名称；否）',
    `IS_COMP_RELATION` Nullable(String) COMMENT '是否存在有效的融合关系（包含松耦合、紧耦合、跨域，此口径只判断用户当前是否存在有效的融合关系，不再判断成员组成和指定产品范围）',
    `WO_IF_USE` Nullable(String) COMMENT '融合是否当前在用',
    `is_bd_iptv` Nullable(String) COMMENT '',
    `pro_type` Nullable(String) COMMENT '产品分类（沃家固话。。）',
    `TOTAL_SMS_NUM` Nullable(String) COMMENT '总发送短信条数',
    `TOTAL_OCT_DURATION` Nullable(String) COMMENT '上网时长(固网对应宽带使用情况)数据自201704起可用',
    `FLUX_UP` Nullable(String) COMMENT '上网上行流量(固网对应宽带使用情况)',
    `FLUX_DOWN` Nullable(String) COMMENT '上网下行流量(固网对应宽带使用情况)',
    `total_fee_last01` Nullable(String) COMMENT '分摊后出账收入',
    `total_fee_avg` Nullable(String) COMMENT '前3个月平均ARPU值',
    `flux_mon_last01` Nullable(String) COMMENT '前3个月平均流量',
    `flux_mon_avg` Nullable(String) COMMENT '上月使用流量',
    `CALL_DURATION_avg` Nullable(String) COMMENT '前3个月平均通话时长',
    `CALL_OUT_JF_avg` Nullable(String) COMMENT '前3个月平均主叫通话时长',
    `acct_kd_cnt` Nullable(String) COMMENT '同账户下宽带数',
    `pspt_yw_cnt` Nullable(String) COMMENT '同身份证下移网号码数',
    `acct_yw_cnt` Nullable(String) COMMENT '同账户下移网号码数',
    `is_iptv` Nullable(String) COMMENT '是否有IPTV',
    `is_jt_user` Nullable(String) COMMENT '是否降套用户',
    `app_cs` Nullable(String) COMMENT 'APP使用次数前5',
    `app_sc` Nullable(String) COMMENT 'APP使用时长前5'
)
"""
schema = {
    'table_name': 'dwa_m_cust_percep_predic_mon',
    'order_key': 'month_id',
    'cols': [
        {'name': 'month_id', 'type': 'str', 'comment': '账期', },
        {'name': 'area_no', 'type': 'str', 'comment': '地市编码', },
        {'name': 'area_name', 'type': 'str', 'comment': '地市名称', },
        {'name': 'user_no', 'type': 'str', 'comment': '用户ID', },
        {'name': 'device_number', 'type': 'str', 'comment': '电话号码', },
        {'name': 'cust_no', 'type': 'str', 'comment': '客户ID', },
        {'name': 'cust_name', 'type': 'str', 'comment': '客户名称', },
        {'name': 'cust_type', 'type': 'str', 'comment': '客户类型', },
        {'name': 'city_no', 'type': 'str', 'comment': '县区MAP_CITY', },
        {'name': 'city_name', 'type': 'str', 'comment': '归属县分名称', },
        {'name': 'user_name', 'type': 'str', 'comment': '用户名称', },
        {'name': 'sex', 'type': 'str', 'comment': '性别标识', },
        {'name': 'age', 'type': 'str', 'comment': '用户年龄', },
        {'name': 'channel_no', 'type': 'str',
            'comment': 'DEVELOP_DEPART_ID发展渠道编码', },
        {'name': 'depart_name', 'type': 'str', 'comment': '渠道名称', },
        {'name': 'VIP_CLASS', 'type': 'str', 'comment': 'VIP等级', },
        {'name': 'is_lh', 'type': 'str', 'comment': '是否靓号', },
        {'name': 'INNET_MONTH', 'type': 'str', 'comment': '在网时长', },
        {'name': 'tele_type_desc', 'type': 'str', 'comment': '业务类型', },
        {'name': 'TELE_TYPE_NET', 'type': 'str', 'comment': '总部下发网络类型--移动业务用户', },
        {'name': 'brand_no', 'type': 'str', 'comment': '品牌', },
        {'name': 'CONTACT_NBR', 'type': 'str', 'comment': '联系电话', },
        {'name': 'CREDIT_CLASS', 'type': 'str', 'comment': '信用等级', },
        {'name': 'user_status_desc', 'type': 'str', 'comment': '用户状态', },
        {'name': 'is_fk', 'type': 'str', 'comment': '是否副卡', },
        {'name': 'kd_device_number', 'type': 'str', 'comment': '宽带号码', },
        {'name': 'kd_web_type', 'type': 'str', 'comment': '宽带资费类型', },
        {'name': 'kd_start_date', 'type': 'str', 'comment': '宽带资费开始时间', },
        {'name': 'kd_end_date', 'type': 'str', 'comment': '宽带资费结束时间', },
        {'name': 'kd_rate_value', 'type': 'str', 'comment': '宽带速率', },
        {'name': 'kd_is_qz', 'type': 'str', 'comment': '是否千兆宽带', },
        {'name': 'kd_install_addr', 'type': 'str', 'comment': '装机地址', },
        {'name': 'VILLAGE_NO', 'type': 'str', 'comment': '小区编码', },
        {'name': 'TERM_NETWORK_TYPE', 'type': 'str', 'comment': '终端制式', },
        {'name': 'TERM_BRAND', 'type': 'str', 'comment': '终端品牌', },
        {'name': 'TERM_MODE', 'type': 'str', 'comment': '终端型号', },
        {'name': 'TERM_SYSTEM', 'type': 'str', 'comment': '操作系统', },
        {'name': 'TERM_MIZE_TYPE', 'type': 'str', 'comment': '联通U/电信T/移动定制M', },
        {'name': 'TERM_UNICOM_TYPE', 'type': 'str',
            'comment': '终端最高登录联通网络能力为联通4G/3G/2G', },
        {'name': 'TERM_REGISTER_TIME', 'type': 'str', 'comment': '换机时间', },
        {'name': 'is_2kc', 'type': 'str', 'comment': '是否2卡槽（单双卡）', },
        {'name': 'product_id', 'type': 'str', 'comment': '产品（PRODUCT_ID）', },
        {'name': 'product_name', 'type': 'str', 'comment': '产品名称', },
        {'name': 'PROD_TYPE', 'type': 'str',
            'comment': '产品大类DWCODE.DIM_PROD_TYPE', },
        {'name': 'PURCHASE_IF_USE', 'type': 'str', 'comment': '合约是否当前在用', },
        {'name': 'PURCHASE_TYPE', 'type': 'str', 'comment': '合约类型', },
        {'name': 'PURCHASE_START_DATE', 'type': 'str', 'comment': '合约开始时间', },
        {'name': 'PURCHASE_END_DATE', 'type': 'str', 'comment': '合约结束时间', },
        {'name': 'is_card', 'type': 'str', 'comment': '是否上网卡', },
        {'name': 'is_cndx', 'type': 'str', 'comment': '是否承诺低消用户', },
        {'name': 'start_date', 'type': 'str', 'comment': '承诺低消生效时间', },
        {'name': 'is_bjl_u', 'type': 'str', 'comment': '是否冰激凌套餐用户', },
        {'name': 'user_type', 'type': 'str', 'comment': '用户类型（2/3/4/5G--采用登网口径）', },
        {'name': 'total_fee', 'type': 'str', 'comment': 'ARPU（元/月）', },
        {'name': 'call_duration', 'type': 'str', 'comment': 'MOU（分钟/月）', },
        {'name': 'CALL_OUT_JF', 'type': 'str', 'comment': '通话主叫计费时长', },
        {'name': 'CALL_IN_JF', 'type': 'str', 'comment': '通话被叫计费时长', },
        {'name': 'CALL_ROAM_JF', 'type': 'str', 'comment': '通话漫游计费时长', },
        {'name': 'flux_dou', 'type': 'str', 'comment': 'DOU（MB/月）', },
        {'name': 'FLUX_2G', 'type': 'str', 'comment': '2G流量', },
        {'name': 'FLUX_3G', 'type': 'str', 'comment': '3G流量', },
        {'name': 'FLUX_4G', 'type': 'str', 'comment': '4G流量', },
        {'name': 'FLUX_5G', 'type': 'str',
            'comment': '5G流量(新增字段数据自202004账期起)', },
        {'name': 'is_ll_ct', 'type': 'str', 'comment': '是否流量超套（否：0；是：超套多少费用）', },
        {'name': 'is_yy_ct', 'type': 'str', 'comment': '是否语音超套（否：0；是：超套多少费用）', },
        {'name': 'product_name_5g_sjb', 'type': 'str', 'comment': '是否办理5G升级包(办理的升级包名称；否）', },
        {'name': 'IS_COMP_RELATION', 'type': 'str',
            'comment': '是否存在有效的融合关系（包含松耦合、紧耦合、跨域，此口径只判断用户当前是否存在有效的融合关系，不再判断成员组成和指定产品范围）', },
        {'name': 'WO_IF_USE', 'type': 'str', 'comment': '融合是否当前在用', },
        {'name': 'is_bd_iptv', 'type': 'str', 'comment': '', },
        {'name': 'pro_type', 'type': 'str', 'comment': '产品分类（沃家固话。。）', },
        {'name': 'TOTAL_SMS_NUM', 'type': 'str', 'comment': '总发送短信条数', },
        {'name': 'TOTAL_OCT_DURATION', 'type': 'str',
            'comment': '上网时长(固网对应宽带使用情况)数据自201704起可用', },
        {'name': 'FLUX_UP', 'type': 'str',
            'comment': '上网上行流量(固网对应宽带使用情况)', },
        {'name': 'FLUX_DOWN', 'type': 'str',
            'comment': '上网下行流量(固网对应宽带使用情况)', },
        {'name': 'total_fee_last01', 'type': 'str', 'comment': '分摊后出账收入', },
        {'name': 'total_fee_avg', 'type': 'str', 'comment': '前3个月平均ARPU值', },
        {'name': 'flux_mon_last01', 'type': 'str', 'comment': '前3个月平均流量', },
        {'name': 'flux_mon_avg', 'type': 'str', 'comment': '上月使用流量', },
        {'name': 'CALL_DURATION_avg', 'type': 'str', 'comment': '前3个月平均通话时长', },
        {'name': 'CALL_OUT_JF_avg', 'type': 'str', 'comment': '前3个月平均主叫通话时长', },
        {'name': 'acct_kd_cnt', 'type': 'str', 'comment': '同账户下宽带数', },
        {'name': 'pspt_yw_cnt', 'type': 'str', 'comment': '同身份证下移网号码数', },
        {'name': 'acct_yw_cnt', 'type': 'str', 'comment': '同账户下移网号码数', },
        {'name': 'is_iptv', 'type': 'str', 'comment': '是否有IPTV', },
        {'name': 'is_jt_user', 'type': 'str', 'comment': '是否降套用户', },
        {'name': 'app_cs', 'type': 'str',  'comment': 'APP使用次数前5', },
        {'name': 'app_sc', 'type': 'str',  'comment': 'APP使用时长前5', },
    ]
}


def load():
    tab = FileTable(
        dir_path=root_dir,
        match_pattern=match_pattern,
        sep='\u0005',
        schema=schema,
    )
    tab.dump_to_ck(index_col=False)